# Generated by Django 6.0.3 on 2026-05-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_rename_apointment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
